import {Miniflare,convertV4MiniflareOptions} from 'miniflare';import {randomBytes,createHash} from 'node:crypto';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const digest=value=>createHash('sha256').update(value).digest('base64url');const raw=randomBytes(32),code=`room1.${raw.toString('base64url')}`;const config={fingerprint:digest(raw)},passwords={};
for(const user of ['nad','maria']){passwords[user]=randomBytes(32).toString('base64url');config[user]={salt:user,hash:digest(`${user}:${passwords[user]}`)};}
const phrases={nad:'orchid harbor velvet mountain',maria:'copper meadow lantern river'};
const mf=new Miniflare(convertV4MiniflareOptions({modules:true,scriptPath:'dist/worker.mjs',compatibilityDate:'2026-09-19',compatibilityFlags:['nodejs_compat'],durableObjects:{ROOM:{className:'PrivateRoom',useSQLite:true}},bindings:{AUTH_CONFIG:JSON.stringify(config)}}));let browser;
try{
  const base=(await mf.ready).href;browser=await chromium.launch({channel:'msedge',headless:true});const errors=[],posts=[];
  const newPage=async(mobile=false)=>{const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1365,height:900},isMobile:mobile,hasTouch:mobile});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST')posts.push(request.postData()||'');});return page;};
  const initial=async(page,user)=>{await page.goto(base);await page.locator('#user').selectOption(user);await page.locator('#password').fill(passwords[user]);await page.locator('#login-submit').click();await page.locator('#recovery').fill(code);await page.locator('#unlock-form .primary').click();await page.locator('#passphrase-dialog').waitFor({state:'visible'});};
  const nad=await newPage(),maria=await newPage(true);await initial(nad,'nad');await nad.locator('#setup-skip').click();await nad.locator('#draft').fill('History created before passphrase setup');await nad.locator('#send').click();await nad.getByText('History created before passphrase setup',{exact:true}).waitFor();
  await nad.locator('#setup-open').click();await mkdir('test-artifacts',{recursive:true});await nad.screenshot({path:'test-artifacts/passphrase-setup.png'});
  await nad.locator('#new-passphrase').fill(phrases.nad);await nad.locator('#confirm-passphrase').fill('a completely different test phrase');await nad.locator('#setup-save').click();await nad.getByText('The two passphrases do not match.',{exact:true}).waitFor();
  const save=async(page,user)=>{await page.locator('#new-passphrase').fill(phrases[user]);await page.locator('#confirm-passphrase').fill(phrases[user]);await page.locator('#setup-save').click();await page.locator('#setup-success').waitFor({state:'visible'});await page.locator('#setup-done').click();};
  await save(nad,'nad');await initial(maria,'maria');await maria.screenshot({path:'test-artifacts/passphrase-mobile.png'});await save(maria,'maria');await maria.getByText('History created before passphrase setup',{exact:true}).waitFor();
  // Fresh browser: only the new passphrase, no original password or history key.
  for(const user of ['nad','maria']){const page=await newPage(user==='maria');await page.goto(base);await page.locator('#user').selectOption(user);await page.locator('#password').fill(phrases[user]);await page.locator('#login-submit').click();await page.locator('#room').waitFor({state:'visible'});await page.getByText('History created before passphrase setup',{exact:true}).waitFor();assert.equal(await page.locator('#unlock-form').isVisible(),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const storage=await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}));assert.equal(storage.includes(phrases[user]),false);assert.equal(storage.includes(code),false);await page.locator('#lock').click();await page.locator('#gate').waitFor({state:'visible'});assert.equal(await page.locator('#messages').textContent(),'');}
  // Explicit original-kit recovery still works after enrollment.
  const recovery=await newPage();await recovery.goto(base);await recovery.locator('#use-kit').click();await recovery.locator('#password').fill(passwords.nad);await recovery.locator('#login-submit').click();await recovery.locator('#recovery').fill(code);await recovery.locator('#unlock-form .primary').click();await recovery.getByText('History created before passphrase setup',{exact:true}).waitFor();
  const payloads=posts.join('\n');for(const phrase of Object.values(phrases))assert.equal(payloads.includes(phrase),false);assert.equal(payloads.includes(code),false);assert.equal(payloads.includes(raw.toString('base64url')),false);assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile setup, mismatch handling, two independent passphrases, fresh-browser history access, original-kit recovery, no plaintext passphrases or recovery keys sent or stored.');
}finally{await browser?.close();await mf.dispose();}
